# ==============================================================================
# digest.py - WEEKLY DIGEST COMPILER & EXECUTIVE VIEW INTERFACE
# ==============================================================================
# Functional Overview:
# This compiler module transforms raw logs into curated content ready for distribution. It:
#   1. Resolves workspace configurations and scans target datastores.
#   2. Extracts logged articles, automatically stripping truncation artifacts ('...').
#   3. Packages entries into a dense token array string, utilizing Groq Llama 3.1 
#      to generate publication-ready Premium Markdown newsletters.
#   4. Outputs a styled text file to disk for copy-paste deployment.
#   5. Runs a regex-cleansed, beautifully spaced ASCII box preview in the terminal window, 
#      eliminating layout-breaking character-cell shifting anomalies.
# ==============================================================================

import os
import re
from datetime import datetime
from groq import Groq
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from dotenv import load_dotenv

if os.path.exists("env"):
    load_dotenv(dotenv_path="env")
else:
    load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def connect_google_sheets():
    """Establishes an authorized sheet API connection stream context."""
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds = ServiceAccountCredentials.from_json_keyfile_name("credentials.json", scope)
    client_gs = gspread.authorize(creds)
    return client_gs.open("TPF Newsletter Research").sheet1


def load_articles_from_sheet():
    """Fetches high-fidelity database dict logs out of Google Sheets workspace sheets."""
    sheet = connect_google_sheets()
    return sheet.get_all_records()


def load_articles_from_file():
    """
    Parses and strips internal Unicode table border vectors from output.txt 
    to rebuild a dictionary collection for compilation.
    
    Returns:
        list: Structured article dictionaries containing tracking fields.
    """
    articles = []
    if os.path.exists("output.txt"):
        with open("output.txt", "r", encoding="utf-8") as f:
            lines = f.readlines()
            for line in lines:
                line = line.strip()
                # Bypasses graphical box framework dividers and header row labels.
                if not line or any(line.startswith(c) for c in ["┌", "├", "└"]) or "Source Category" in line:
                    continue
                
                if "│" in line:
                    # Splits cell tokens cleanly across spatial divider line characters.
                    parts = [p.strip() for p in line.split("│") if p.strip()]
                    if len(parts) >= 7:
                        clean_link = parts[6]
                        # Essential URL preservation handler: Strips trailing visual 
                        # ellipsis formatting elements added by the ingestion tool.
                        if clean_link.endswith("..."):
                            clean_link = clean_link[:-3].strip()
                            
                        articles.append({
                            "Date":            parts[0],
                            "Source":          parts[1],
                            "Source Category": parts[2],
                            "Title":           parts[3],
                            "Category":        parts[4],
                            "Summary":         parts[5],
                            "Link":            clean_link
                        })
    return articles


def print_beautiful_console_box(markdown_text):
    """
    Transforms messy Markdown syntax layouts into a spaced, 
    highly legible CLI dashboard preview box.
    
    Args:
        markdown_text (str): Complete raw Markdown data generated by the model.
    """
    lines = markdown_text.split("\n")
    max_w = 95  # Constrained character boundary limits for perfect text-wall framing.
    
    top_line = "┌" + "─" * (max_w + 2) + "┐"
    mid_line = "├" + "─" * (max_w + 2) + "┤"
    bot_line = "└" + "─" * (max_w + 2) + "┘"
    
    print("\n" + top_line)
    print(f"│ {'WEEKLY RESEARCH DIGEST PRODUCTION PREVIEW':^{max_w}} │")
    print(mid_line)
    print(f"│ {'':<{max_w}} │")  # Cushion padding row provides structural spacing.

    for line in lines:
        l = line.strip()
        
        # Preserves line padding breaks to let paragraphs breathe.
        if not l:
            print(f"│ {'':<{max_w}} │")
            continue
            
        # Converts structural horizontal markdown breaks into solid internal borders.
        if l.startswith("---"):
            print(f"│ {'':<{max_w}} │")
            print(mid_line)
            print(f"│ {'':<{max_w}} │")
            continue
            
        # Standardizes markdown headers to render neatly in terminal displays.
        if l.startswith("#"):
            l = re.sub(r"^#+\s*", "══▶  ", l).upper()
            print(f"│ {'':<{max_w}} │")
            print(f"│ {l:<{max_w}} │")
            print(f"│ {'':<{max_w}} │")
            continue

        # Replaces raw markdown asterisks with clean bullet points.
        if l.startswith("*"):
            l = re.sub(r"^\*\s*", "  • ", l)
            
        # CRITICAL REGEX & STRING CLEANUP:
        # Drops clutter characters like double-asterisks, backticks, and blockquote tags.
        l = l.replace("**", "").replace("`", "").replace(">", "")
        
        # STRATEGIC FIX: Strips out graphic emojis ONLY during the terminal preview run.
        # This prevents wide multi-byte emoji fonts from distorting the right box boundary alignment.
        l = l.replace("📰", "").replace("🎯", "").replace("🚀", "").replace("🛠️", "").replace("🌐", "").replace("🔬", "").replace("📄", "").replace("🐦", "").replace("💡", "").replace("⚡", "")
        
        # Re-formats markdown links to read as standard text references.
        l = re.sub(r"\[(.*?)\]\((.*?)\)", r"\1 (\2)", l)
        l = l.strip()

        # INTERNAL WORD WRAPPING ENGINE:
        # Prevents long paragraphs from clipping out or overflowing past the right border wall.
        if len(l) > max_w:
            words = l.split(" ")
            current_chunk = ""
            for word in words:
                if len(current_chunk) + len(word) + 1 > max_w:
                    print(f"│ {current_chunk:<{max_w}} │")
                    current_chunk = "    " + word  # Indents wrapped line fragments for readability.
                else:
                    if current_chunk == "    ":
                        current_chunk = f"    {word}".strip()
                    else:
                        current_chunk = f"{current_chunk} {word}".strip()
            if current_chunk:
                print(f"│ {current_chunk:<{max_w}} │")
        else:
            print(f"│ {l:<{max_w}} │")
            
    print(f"│ {'':<{max_w}} │")
    print(bot_line + "\n")


def generate_digest(articles):
    """
    Assembles extracted database items, passes them through editorial layout directives
    via Llama 3.1, saves the output, and triggers the CLI preview.
    
    Args:
        articles (list): Curated item structures processed from source feeds.
    """
    if not articles:
        print("+------------------------------------------------------------+")
        print("| ❌ No dataset entries available to compile inside database |")
        print("+------------------------------------------------------------+")
        return

    # Compiles raw data rows into an optimized context prompt block.
    article_text = ""
    for i, a in enumerate(articles, 1):
        article_text += f"""
{i}. [{a.get('Category', 'General')}] {a.get('Title', '')}
   Source: {a.get('Source', '')} ({a.get('Source Category', '')})
   Summary: {a.get('Summary', '')}
   Link: {a.get('Link', '')}
---"""

    # High-impact corporate editorial instructions targeting TPF newsletter layout criteria.
    prompt = f"""You are a professional editorial director writing a premium weekly AI & Product newsletter for The Product Folks (TPF). 
Transform the raw input data below into a beautifully formatted, highly engaging, and modern Markdown newsletter layout.

CRITICAL FORMATTING RULES:
1. Never break a bullet point summary or single reference item into multiple text lines. Ensure every distinct bullet stays on its own continuous line block to prevent broken layouts.
2. Embed raw URLs elegantly inside explicit masked Markdown hyperlinks: [Read full story](URL), [Source Link](URL), or [View Launch](URL).
3. If a link URL appears incomplete or cut short, make your best effort to preserve the visible domain path context smoothly.
4. Utilize contextual editorial emojis and crisp bolding hierarchies to ensure rapid skimmability.

Format the output EXACTLY matching this visual template schema:

# 📰 The Weekly AI & Product Digest
**Edition: {datetime.now().strftime("%B %d, %Y")}** ⚡ *Curated insights from 9 leading global sources by the TPF AI Research Agent.*

---

## 🎯 Top Themes This Week
*(Synthesize the core industry narratives into 3-4 high-impact, continuous bullet points. Mention key sources in backticks.)*
* **Trend Title:** Broad analytical description of the macro trend shifting markets. `(Source Name)`

---

## 🚀 Key Launches & Tools
*(List outstanding product drops, tools, or research ecosystem programs using clean bolded elements.)*
* 🛠️ **[Tool Name]** — Functional description context highlighting user utility. `[{{Source Name}}]` — [View Launch](Link)

---

## 💰 Funding & Industry News
*(Document financing actions, corporate structures, and platform shifts.)*
* 🌐 Clear narrative statement of the business milestone or market dynamic. `({{Source Name}})` — [Read full story](Link)

---

## 🔬 Research & Model Releases
*(Highlight mathematical paradigms, model frameworks, and enterprise benchmarking/safety datasets.)*
* 📄 **[Paper or Model Name]**: High-level evaluation of architectural impact or system performance. `({{Source Name}})` — [Source Reference](Link)

---

## 🐦 From X / Twitter
*(Provide a clear overview or bullet point if data records are found. If streams are blank or experiencing external proxy rate-limits, output exactly: "No notable posts or threads from AI researchers/leaders were found this week due to proxy upstream rate-limiting.")*

---

## 💡 Insight of the Week
> ⚡ **The Big Picture Takeaway:**
> (Provide a deeply analytical concluding paragraph summarizing the friction between rapid product drops and emerging data guardrails.)

---

Raw Tracking Records to Compile:
{article_text}

Write the premium newsletter now:"""

    print("+------------------------------------------------------------------------------+")
    print("| ⚙️  PROCESSING IN PROGRESS: COMPILING WEEKLY RESEARCH DIGEST DOSSIER...      |")
    print("+------------------------------------------------------------------------------+\n")

    # Connects to the high-throughput pool using llama-3.1-8b-instant to bypass daily blocks.
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=2500,
        temperature=0.3
    )

    digest = response.choices[0].message.content

    # Writes the final text to disk, ensuring all emojis and markdown links remain intact.
    filename = f"digest_{datetime.now().strftime('%Y-%m-%d')}.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(digest)

    # Triggers layout renderer engine tool to display the formatted preview in console logs.
    print_beautiful_console_box(digest)

    print("+------------------------------------------------------------------------------+")
    print(f"| ✅ SUCCESS: Production-Grade digest saved as: {filename:<30} |")
    print("| 📋 Workspace assets optimized for direct copy-paste deployment.               |")
    print("+------------------------------------------------------------------------------+")


if __name__ == "__main__":
    print("+------------------------------------------------------------------------------+")
    print("| ⚙️  SYSTEM PIPELINE DIAGNOSTIC REPORT                                         |")
    print("+------------------------------------------------------------------------------+")
    try:
        articles = load_articles_from_sheet()
        print(f"|  Cloud Sheet Sync: Success ({len(articles):<2} database rows found)                  |")
    except Exception as e:
        print("|  Cloud Interface Status: Offline (credentials.json missing)                  |")
        print("|  Recovery Action: Activating local table processing engine matrix...         |")
        articles = load_articles_from_file()
        print(f"|  Local Database Registry: {len(articles):<2} relevant data records loaded successfully      |")
    print("+------------------------------------------------------------------------------+\n")

    generate_digest(articles)